### ISSUE TITLE
Unicode Error

### ISSUE THREAD

**Issue by digitalwiz** [kallqvist/skillshare-downloader#13]
I am getting the following error

C:\code>python example.py
Traceback (most recent call last):
  File "example.py", line 10, in <module>
    dl.download_course_by_url('https://www.skillshare.com/classes/How-to-Get-a-Job-as-a-Front-End-Web-Developer-The-Complete-Step-by-Step-Guide/1711276638?via=search-layout-grid')
  File "C:\code\downloader.py", line 36, in download_course_by_url
    self.download_course_by_class_id(m.group(1))
  File "C:\code\downloader.py", line 62, in download_course_by_class_id
    slugify(teacher_name),
  File "C:\Python27\lib\site-packages\slugify.py", line 26, in slugify
    unicodedata.normalize('NFKD', string)
TypeError: normalize() argument 2 must be unicode, not str

**Comment by digitalwiz** [comment]
Above error is Python 2.

Tried 3 got this error:

```
C:\code>py example.py
Traceback (most recent call last):
  File "example.py", line 10, in <module>
    dl.download_course_by_url('https://www.skillshare.com/classes/How-to-Get-a-Job-as-a-Front-End-Web-Developer-The-Complete-Step-by-Step-Guide/1711276638?via=search-layout-grid')
  File "C:\code\downloader.py", line 36, in download_course_by_url
    self.download_course_by_class_id(m.group(1))
  File "C:\code\downloader.py", line 62, in download_course_by_class_id
    slugify(teacher_name),
  File "C:\Users\irara\AppData\Local\Programs\Python\Python37\lib\site-packages\slugify.py", line 24, in slugify
    unicode(
NameError: name 'unicode' is not defined

```
Not sure what version of Python I am supposed to use.

**Comment by kallqvist** [comment]
Hmm, python3 is the recommended version to use.
I'm using python 3.7 myself and am able to download the URL in your example.

The error seems to happen in another library, my suspicion here is that you might have a older version of that.
Could you try to first do this in a terminal:
`
pip install --upgrade python-slugify
`
and then try to run this again?

If that doesn't do it, please run:
`
pip freeze
`
and paste the output as a comment here.
I'm at least >50% certain that this is about old versions of libraries not being python3-friendly :)

**Comment by kallqvist** [comment]
Hmm, you have an extra library called slugify.
Not sure but maybe that could cause some issues.

Here's my pip freeze:
`
certifi==2018.11.29
chardet==3.0.4
idna==2.8
python-slugify==2.0.1
requests==2.21.0
Unidecode==1.0.23
urllib3==1.24.1
`

Try uninstalling it and see if problem persists.
