### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by andrewfashion** [kallqvist/skillshare-downloader#29]
I'm a python noob :( any help would be awesome

I run the command: docker-compose run --rm ssdl python example.py

and get this:

Traceback (most recent call last):
  File "example.py", line 10, in <module>
    dl.download_course_by_url('https://www.skillshare.com/classes/Art-Fundamentals-in-One-Hour/189505397')
  File "/code/downloader.py", line 36, in download_course_by_url
    self.download_course_by_class_id(m.group(1))
  File "/code/downloader.py", line 39, in download_course_by_class_id
    data = self.fetch_course_data_by_class_id(class_id=class_id)
  File "/code/downloader.py", line 106, in fetch_course_data_by_class_id
    res = requests.get(
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1271, in _send_request
    self.putheader(hdr, value)
  File "/usr/local/lib/python3.8/http/client.py", line 1203, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2026' in position 399: ordinal not in range(256)

**Comment by kallqvist** [comment]
Hey, please check that nothing "weird" got copied together with your cookie.
You for example must hit enter in browser console to get full value and not a trimmed string, that's maybe what have happened here?
'\u2026' is a special character that could be rendered as '...' but the cookie should never contain such a character
