### ISSUE TITLE
Not able to download any video except the welcome or first video

### ISSUE THREAD

**Issue by aksingh-apptio** [kallqvist/skillshare-downloader#47]
Traceback (most recent call last):
  File "/code/example.py", line 11, in <module>
    dl.download_course_by_url('https://www.skillshare.com/classes/How-to-Ace-your-Exams-The-Method-to-Mastery/1787903253')
  File "/code/downloader.py", line 36, in download_course_by_url
    self.download_course_by_class_id(m.group(1))
  File "/code/downloader.py", line 83, in download_course_by_class_id
    raise Exception('Failed to read video ID from data')
Exception: Failed to read video ID from data

**Comment by w3bdesign** [comment]
@aksingh-apptio 

1. Check that you have installed the requirements correctly. You need to do:

```
pip install -r requirements.txt
``` 
or
```
python3 -m pip install -r requirements.txt
```

2. Doublecheck that the cookie was pasted correctly.

3. Try a different course and see if it still happens.

**Comment by mikebluu** [comment]
I have the same problem... already tried those written above my comment, no luck, tried 3 courses, the script only downloads the first video. It would be so useful, but when I have a 50+ videos course, the first one is really useless.

**Comment by 04anubhavv** [comment]
> I have the same problem... already tried those written above my comment, no luck, tried 3 courses, the script only downloads the first video. It would be so useful, but when I have a 50+ videos course, the first one is really useless.

are you using a premium account for cookie?

**Comment by mikebluu** [comment]
> > I have the same problem... already tried those written above my comment, no luck, tried 3 courses, the script only downloads the first video. It would be so useful, but when I have a 50+ videos course, the first one is really useless.
> 
> are you using a premium account for cookie?

If by premium account, you mean the one that is paid, yes, I'm using that. I mean, as long as I can view as many courses as I like, without limitation, I think I have the premium account.

**Comment by 04anubhavv** [comment]
> > > I have the same problem... already tried those written above my comment, no luck, tried 3 courses, the script only downloads the first video. It would be so useful, but when I have a 50+ videos course, the first one is really useless.
> > 
> > 
> > are you using a premium account for cookie?
> 
> If by premium account, you mean the one that is paid, yes, I'm using that. I mean, as long as I can view as many courses as I like, without limitation, I think I have the premium account.

I can download any course (except few exceptions) I think you put the cookie incorrectly 
by the way you can try this https://www.youtube.com/watch?v=_2dOZUu-fsw
It was working

**Comment by 04anubhavv** [comment]
> > > I have the same problem... already tried those written above my comment, no luck, tried 3 courses, the script only downloads the first video. It would be so useful, but when I have a 50+ videos course, the first one is really useless.
> > 
> > 
> > are you using a premium account for cookie?
> 
> If by premium account, you mean the one that is paid, yes, I'm using that. I mean, as long as I can view as many courses as I like, without limitation, I think I have the premium account.

your cookie should look like this 
![image](https://i.imgur.com/ZSc81Sf.png)

**Comment by mikebluu** [comment]
> > > > I have the same problem... already tried those written above my comment, no luck, tried 3 courses, the script only downloads the first video. It would be so useful, but when I have a 50+ videos course, the first one is really useless.
> > > 
> > > 
> > > are you using a premium account for cookie?
> > 
> > 
> > If by premium account, you mean the one that is paid, yes, I'm using that. I mean, as long as I can view as many courses as I like, without limitation, I think I have the premium account.
> 
> I can download any course (except few exceptions) I think you put the cookie incorrectly
> by the way you can try this https://www.youtube.com/watch?v=_2dOZUu-fsw
> It was working

Your method works well! I downloaded with it, it's flawless.

**Comment by mikebluu** [comment]
> > > > I have the same problem... already tried those written above my comment, no luck, tried 3 courses, the script only downloads the first video. It would be so useful, but when I have a 50+ videos course, the first one is really useless.
> > > 
> > > 
> > > are you using a premium account for cookie?
> > 
> > 
> > If by premium account, you mean the one that is paid, yes, I'm using that. I mean, as long as I can view as many courses as I like, without limitation, I think I have the premium account.
> 
> your cookie should look like this
> ![image](https://camo.githubusercontent.com/dcdec2a5d33548b126deff0d6aa31a496c03e9e9a185ede548c362c641a8c4a6/68747470733a2f2f692e696d6775722e636f6d2f5a5363383153662e706e67)

That was the problem... I didn't copy the whole thing, now works like a charm! Thanks for your fast support, have a nice one.

**Comment by sandeepthukral** [comment]
I think I copied the cookie properly. I have a premium trial. I am only interested in seeing how this code works. 
I am facing the same issue as reported. Downloads the first video (trailer) and then stops.
My cookie looks like this 
![image](https://user-images.githubusercontent.com/1406497/106708230-cebe4880-65f2-11eb-85e4-51171b1c2552.png)

I am using the docker solution, so installing the requirements should not be an issue.

**Comment by 04anubhavv** [comment]
@sandeepthukral  you need a premium account to download all videos

you can use this if you don't have premium account https://www.youtube.com/watch?v=_2dOZUu-fsw

**Comment by 04anubhavv** [comment]
> I think I copied the cookie properly. I have a premium trial. I am only interested in seeing how this code works.
> I am facing the same issue as reported. Downloads the first video (trailer) and then stops.
> My cookie looks like this
> ![image](https://user-images.githubusercontent.com/1406497/106708230-cebe4880-65f2-11eb-85e4-51171b1c2552.png)
> 
> I am using the docker solution, so installing the requirements should not be an issue.

try log out and then log in and then ask cookie 
I  think this will help 

you can also see this repo https://github.com/04anubhavv/Skillshare-dl

It also contains subtitle and resource downloading
