### ISSUE TITLE
Name 'unicode' is not defined

### ISSUE THREAD

**Issue by daliborb20** [kallqvist/skillshare-downloader#49]
Traceback (most recent call last):
  File "example.py", line 10, in <module>
    dl.download_course_by_url('')
  File "/home/boogyman/skillshare-downloader/code/downloader.py", line 38, in download_course_by_url
    self.download_course_by_class_id(m.group(1))
  File "/home/boogyman/skillshare-downloader/code/downloader.py", line 64, in download_course_by_class_id
    slugify(teacher_name),
  File "/home/boogyman/.local/lib/python3.8/site-packages/slugify.py", line 24, in slugify
    unicode(
NameError: name 'unicode' is not defined

**Comment by VicVaquero** [comment]
@daliborb20 I got the same error as you. I see that you are using python3 and `unicode` is not longer supported (or was renamed `str`, idk). I tried to solve this by changing the slugify.py but without much success. Instead, I ran it on a venv with python2.7. However, I still got a similar error but I was able to fix it by modifying a line in the slugify.py.

```
def slugify(string):

    """
    Slugify a unicode string.

    Example:

        >>> slugify(u"Héllø Wörld")
        u"hello-world"

    """

    return re.sub(r'[-\s]+', '-',
            unicode(
                re.sub(r'[^\w\s-]', '',
                    unicodedata.normalize('NFKD', unicode(string,  'utf-8'))
                    .encode('ascii', 'ignore'))
                .strip()
                .lower()))
```

hope this helps :)

**Comment by shadow-hunte** [comment]
just download python-slugify-4.0.0 and install it.  Newer ones will not work, uninstall any latest version you have already installed

**Comment by Helaluzzaman** [comment]
install python-slugify not slugify
