### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by kumaranjeya** [kallqvist/skillshare-downloader#64]
Hi,
I'm getting following error for recent courses (Using Python 3.9 and not effecting old courses):

ClassName : Lighitng for Games 101 : Fundamentals of Lighting in UE4 _ Part 2 + Lighting Blueprints Office
Traceback (most recent call last):
  File "E:\_Skillshare\downloader.py", line 26, in <module>
    dl.download_course_by_url(url, boolSubtitle, boolResources)
  File "E:\_Skillshare\skillshare.py", line 38, in download_course_by_url
    self.download_course_by_class_id(class_id, boolSubtitle, boolResources)
  File "E:\_Skillshare\skillshare.py", line 98, in download_course_by_class_id
    for u in data['_embedded']['units']['_embedded']['units']:
TypeError: list indices must be integers or slices, not str

Any ideas to resolve this issue? Thank you.

**Comment by grishatop1** [comment]
I've figured it out, this happens not to the all courses but most of them I've tried.
Here is the fix, just replace entire `for` loop on line `70` with this:
```
try:
            for u in data['_embedded']['units']['_embedded']['units']:
                for s in u['_embedded']['sessions']['_embedded']['sessions']:
                    video_id = None

                    if 'video_hashed_id' in s and s['video_hashed_id']:
                        video_id = s['video_hashed_id'].split(':')[1]
                    elif 'video_thumbnail_url' in s and s['video_thumbnail_url']:
                        video_id = s['video_thumbnail_url'].split('/')[6]

                    if not video_id:
                        # NOTE: this happens sometimes...
                        # seems random and temporary but might be some random
                        # server-side check on user-agent etc?
                        # ...think it's more stable now with those set to
                        # emulate an android device
                        raise Exception('Failed to read video ID from data')

                    s_title = s['title']

                    if self.is_unicode_string(s_title):
                        s_title = s_title.encode('ascii', 'replace')  # ignore any weird char

                    file_name = '{} - {}'.format(
                        str(s['index'] + 1).zfill(2),
                        slugify(s_title),
                    )

                    self.download_video(
                        fpath='{base_path}/{session}.mp4'.format(
                            base_path=base_path,
                            session=file_name,
                        ),
                        video_id=video_id,
                    )

                    print('')
        except TypeError:
            for s in data['_embedded']['sessions']['_embedded']['sessions']:
                video_id = None

                if 'video_hashed_id' in s and s['video_hashed_id']:
                    video_id = s['video_hashed_id'].split(':')[1]
                elif 'video_thumbnail_url' in s and s['video_thumbnail_url']:
                    video_id = s['video_thumbnail_url'].split('/')[6]

                if not video_id:
                    # NOTE: this happens sometimes...
                    # seems random and temporary but might be some random
                    # server-side check on user-agent etc?
                    # ...think it's more stable now with those set to
                    # emulate an android device
                    raise Exception('Failed to read video ID from data')

                s_title = s['title']

                if self.is_unicode_string(s_title):
                    s_title = s_title.encode('ascii', 'replace')  # ignore any weird char

                file_name = '{} - {}'.format(
                    str(s['index'] + 1).zfill(2),
                    slugify(s_title),
                )

                self.download_video(
                    fpath='{base_path}/{session}.mp4'.format(
                        base_path=base_path,
                        session=file_name,
                    ),
                    video_id=video_id,
                )

                print('')
```

**Comment by t3rminalx** [comment]
I tried the above to try and solve the same error but I'm getting the following error when I try to run it. Have you any idea what could fix the 'data' not defined error please?
```
Traceback (most recent call last):
  File "/home/anthony/skillshare-downloader/skillshare-downloader/code/example.py", line 1, in <module>
    from downloader import Downloader
  File "/home/anthony/skillshare-downloader/skillshare-downloader/code/downloader.py", line 9, in <module>
    class Downloader(object):
  File "/home/anthony/skillshare-downloader/skillshare-downloader/code/downloader.py", line 111, in Downloader
    for u in data['_embedded']['units']['_embedded']['units']:
NameError: name 'data' is not defined
```
