### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by t3rminalx** [kallqvist/skillshare-downloader#69]
`
Traceback (most recent call last):
File "/home/anthony/skillshare-downloader/skillshare-downloader/code/example.py", line 8, in <module>
    dl.download_course_by_url('https://www.skillshare.com/classes/Boudoir-Portrait-Retouching-for-Photographers/829829877/projects')
  File "/home/anthony/skillshare-downloader/skillshare-downloader/code/downloader.py", line 36, in download_course_by_url
    self.download_course_by_class_id(m.group(1))
  File "/home/anthony/skillshare-downloader/skillshare-downloader/code/downloader.py", line 70, in download_course_by_class_id
    for u in data['_embedded']['units']['_embedded']['units']:
TypeError: list indices must be integers or slices, not str
`

**Comment by CodingButter** [comment]
I'm experiencing the same issue. Not familiar enough with python or the current code base to resolve the issue myself. Any idea what the solution might be?

**Comment by CodingButter** [comment]
Fixed the issue with this pull request https://github.com/kallqvist/skillshare-downloader/pull/70

**Comment by CrissGill** [comment]
Hello friends if you want skill share free account just join my telegram group I am not promoting the telegram I just want to help you all guys
Thank you 👍
https://t.me/SkillshareAcs
