### ISSUE TITLE
Exception: Failed to read video ID from data

### ISSUE THREAD

**Issue by notmanan0** [kallqvist/skillshare-downloader#71]
Downloading /content/Skillshare/hamza-ahmed/social-skills-masterclass-make-friends-online-in-the-gym-and-at-school/01 - what-s-it-like-having-a-good-group-of-friends.mp4...
Video already downloaded, skipping...

Traceback (most recent call last):
  File "/root/.Skillshare-DL/dl.py", line 16, in <module>
    main()
  File "/root/.Skillshare-DL/dl.py", line 11, in main
    dl.download_course_by_url(course_url)
  File "/root/.Skillshare-DL/skillshare.py", line 32, in download_course_by_url
    self.download_course_by_class_id(m.group(1))
  File "/root/.Skillshare-DL/skillshare.py", line 72, in download_course_by_class_id
    raise Exception('Failed to read video ID from data')
Exception: Failed to read video ID from data
Getting this error. Can someone help? Thanks.

**Comment by CrissGill** [comment]
Hello friends if you want skill share free account just join my telegram group I am not promoting the telegram I just want to help you all guys
Thank you 👍
https://t.me/SkillshareAcs
