### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by Chupachis** [kallqvist/skillshare-downloader#8]
Hi there, I'm getting an error when using the script. 

```
C:\Users\***>python D:\skillshare-downloader-master\code\exemple.py
Traceback (most recent call last):
  File "D:\skillshare-downloader-master\code\exemple.py", line 10, in <module>
    dl.download_course_by_url('https://www.skillshare.com/classes/Art-Fundamentals-in-One-Hour/189505397')
  File "D:\skillshare-downloader-master\code\downloader.py", line 24, in download_course_by_url
    self.download_course_by_class_id(m.group(1))
  File "D:\skillshare-downloader-master\code\downloader.py", line 35, in download_course_by_class_id
    if isinstance(teacher_name, unicode):
NameError: name 'unicode' is not defined
```

I thought this might have been an error due to using Python 3 instead or 2.7, but using 2.7 got me another error:

```
C:\Users\***> C:\Python27\python.exe D:\skillshare-downloader-master\code\exemple.py
Traceback (most recent call last):
  File "D:\skillshare-downloader-master\code\exemple.py", line 1, in <module>
    from downloader import Downloader
  File "D:\skillshare-downloader-master\code\downloader.py", line 1, in <module>
    import requests
ImportError: No module named requests
```

I don't really know what could be wrong, so I'm asking the question here, sorry :/

**Comment by Chupachis** [comment]
Trying to use Docker to run the script, I get this error

`PS` D:\skillshare-downloader-master> docker-compose run --rm ssdl python example.py
Traceback (most recent call last):
  File "/code/from-arguments.py", line 14, in <module>
    dl.download_course_by_url(sys.argv[2])
  File "/code/downloader.py", line 23, in download_course_by_url
    raise Exception('Failed to parse class ID from URL')
Exception: Failed to parse class ID from URL``

I don't really know what else to do :/

**Comment by kallqvist** [comment]
Hmm, not sure about python3. It was never really tested with that while this was being written.

Python2.7 should still work, you can try to first run:
```
pip install requests
```
It should most likely fix your second error.

The last error however might be something wrong with the URL or an actual bug in the code.
What does the URL you're trying to download look like?
